### ISSUE TITLE
wallbox charge and heating rod control 

### ISSUE THREAD

**Issue by matthiasrieger** [mwalle/shinelanx-modbus#1]
is it possible to add wallbox charge and heating rod control via modbus tcp? that would save me 10 to 20 watts because i like the idea of having those components at least in different vlan, so that they can not be managed by malfunctioning iobroker or office pc.

i'm not a microcontroller guy, but give try to give it a shot...

btw. can you please give me an idea where to get the 3.3 v from? do i just have to connect the gnd, swclk, swdio to the debugger and power it with usb?

thanks!

**Comment by mwalle** [comment]
> is it possible to add wallbox charge and heating rod control via modbus tcp? that would save me 10 to 20 watts because i like the idea of having those components at least in different vlan, so that they can not be managed by malfunctioning iobroker or office pc.

I'm not sure I get what you want to achieve? Like having a controller program *on* the shine lanx stick? That should be possible in theory. NuttX is an operating system with threads, so you could just write an programm which talks to mbusd and to your heating thing.

> i'm not a microcontroller guy, but give try to give it a shot...
> 
> btw. can you please give me an idea where to get the 3.3 v from? do i just have to connect the gnd, swclk, swdio to the debugger and power it with usb?

Yes. You're already the second one asking. I'll update the README accordingly.
