### ISSUE TITLE
BusPirate instead BusBlaster

### ISSUE THREAD

**Issue by fortschritt311** [mwalle/shinelanx-modbus#2]
Hi.
Is it possible to use a BusPirate Board to flash dapboot?

Mfg Maik

**Comment by mwalle** [comment]
Hi Maik,

this should be possible, see also
https://github.com/openocd-org/openocd/commit/6a4f5a4a6707520b7e12ec4199cd77129ee6436e
where the SWD support for the buspirate adapter was added.

There is also:
https://www.earth.li/~noodles/blog/2015/08/program-fst01-with-buspirate.html

-michael

**Comment by fortschritt311** [comment]
Hello.
Thank you for your reply.
I asked because the BusPirate is much better available.
I'll start with that then.

Greetings Maik

**Comment by mwalle** [comment]
Hi Maik,

cheap stm32 programmer clones (available at amazon for example) are also working.

-michael

**Comment by fortschritt311** [comment]
Hi Michael,

thanks for your support.

I have a question about the connection between buspirate and shineboard :

GND - GND
SWDIO - MOSI
SWCLK - CLK

Does the shineboard need an additional 3.3V voltage for the flash?

I get this error with openocd :

```
Error: timed out while waiting for target halted
TARGET: stm32f1x.cpu - Not halted
```

I have only connected the 3 pins mentioned above, power is supplied via the USB port of the PC. Is it possible that the shineboard must not be connected to the USB while it is being flashed? Then I would have to establish a power supply via the busprate....

Thanks & Greetings
Maik

**Comment by fortschritt311** [comment]
Hi,

i found a solution...
I have to set `reset_config none`  in the stm32f1x.cfg file of openocd.
Then the flash works.

**Comment by mwalle** [comment]
Great to hear!
